#serveur backend
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=rootpassword
    ports:
      - 8080:80
    depends_on:
      - db

#base de données
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data:

# Ajout du réseau pour garantir la communication entre les services
networks:
  default:
    driver: bridge
