

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=rootpassword
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  grafana:
    build:
      context: ./grafana  # Le chemin vers ton Dockerfile Grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000  # Expose le port de Grafana
    depends_on:
      - db  # Grafana dépend de MySQL si tu veux connecter Grafana à la base de données
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Mot de passe pour l'utilisateur admin de Grafana

volumes:
  db_data:

networks:
  default:
    driver: bridge
