services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=rootpassword
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  
  # Service cAdvisor
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8081:8080"  # Expose cAdvisor on port 8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-network

 # Service Node Exporter
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"  # Expose Node Exporter metrics
    networks:
      - app-network

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db  # Grafana dépend de MySQL si tu veux connecter Grafana à la base de données
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    build:
      context: ./prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - app-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

