global:
  scrape_interval: 15s  # Intervalle de collecte par défaut pour Prometheus

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus collecte ses propres métriques
