# Dockerfile pour Grafana
FROM grafana/grafana:latest

EXPOSE 3000

# Copier le fichier JSON du tableau de bord
COPY ./dashboard.json /etc/grafana/provisioning/dashboards/

# Copier le fichier de provisioning
COPY ./dashboard.yaml /etc/grafana/provisioning/dashboards/

# Définir la commande de démarrage (Grafana démarre automatiquement)
CMD [ "/bin/bash", "-c", "/bin/grafana-server -homepath=/usr/share/grafana" ]
